Message display corrections

diff --git a/misybag b/misybag
--- a/misybag
+++ b/misybag
@@ -28,19 +28,19 @@ export TEXTDOMAIN=MisybaG
 #  1. The name of this script.
 help() {
 	local msbg_name=${1}
-	echo $(eval_gettext "Usage: \${msbg_name} [new|sys-install|update] [parameters]")
+	echo -e $(eval_gettext "Usage: \${msbg_name} [new|sys-install|update] [parameters]")
 	echo
-	echo $(eval_gettext "\${msbg_name} new profile_name [dir_name]")
-	echo "  "$(eval_gettext "Create a new MisybaG project using given profile_name in dir_name.")
-	echo "  "$(eval_gettext "profile_name is a MisybaG profile name, i.e. the path of the sub-directory of:")
+	echo -e $(eval_gettext "\${msbg_name} new profile_name [dir_name]")
+	echo -e "  "$(eval_gettext "Create a new MisybaG project using given profile_name in dir_name.")
+	echo -e "  "$(eval_gettext "profile_name is a MisybaG profile name, i.e. the path of the sub-directory of:")
 	echo "${MISYBAG_CONFIG_DIR}/profiles/MisybaG/"
-	echo "  "$(eval_gettext "dir_name is the name of directory where new project will be created. The directory is created if\\nit does not exist. New project is created in current directory if none given.")
+	echo -e "  "$(eval_gettext "dir_name is the name of directory where new project will be created. The\\ndirectory is created if it does not exist. New project is created in current\\ndirectory if none given.")
 	echo
-	echo $(eval_gettext "\${msbg_name} sys-install")
-	echo "  "$(eval_gettext "Install the full target system. This will delete the current content on the target.")
+	echo -e $(eval_gettext "\${msbg_name} sys-install")
+	echo -e "  "$(eval_gettext "Install the full target system. This will delete the current content on the\\ntarget.")
 	echo
-	echo $(eval_gettext "\${msbg_name} update")
-	echo "  "$(eval_gettext "Update the target system, using project configuration.")
+	echo -e $(eval_gettext "\${msbg_name} update")
+	echo -e "  "$(eval_gettext "Update the target system, using project configuration.")
 }
 
 ############
@@ -82,12 +82,12 @@ createMakeConf() {
 new() {
 	# Prepare function environment
 	if [[ -z "${1}" ]]; then
-		echo $(eval_gettext "Missing profile") >&2
+		echo -e $(eval_gettext "Missing profile") >&2
 		exit 1
 	fi
 	local profile_dir="${MISYBAG_CONFIG_DIR}/profiles/MisybaG/${1#/}"
 	if [[ ! -d ${profile_dir} ]]; then
-		echo $(eval_gettext "Profile directory \${profile_dir} does not exist")
+		echo -e $(eval_gettext "Profile directory \${profile_dir} does not exist")
 		exit 1
 	fi
 	profile_dir="$(cd "${profile_dir}"; pwd)"
@@ -107,7 +107,7 @@ new() {
 	local chost=$(emerge --info | grep '^CHOST\s*=' | sed 's/CHOST\s*=\s*"\?\([^"]*\)"\?/\1/')
 	export SYSROOT=/usr/"${chost}"
 	if [[ ! -d "${SYSROOT}" ]]; then
-		echo $(eval_gettext "Missing toolchain directory \${SYSROOT}") >&2
+		echo -e $(eval_gettext "Missing toolchain directory \${SYSROOT}") >&2
 		exit 1
 	fi
 	createMakeConf "${chost}"
@@ -137,9 +137,9 @@ new() {
 	fi
 
 	# Terminated
-	echo $(eval_gettext "Project created on directory:")
+	echo -e $(eval_gettext "Project created on directory:")
 	echo "${project_dir}"
-	echo $(eval_gettext "You should now mount your distant root to:")
+	echo -e $(eval_gettext "You should now mount your distant root to:")
 	echo "${project_dir}"/distroot
 }
 
@@ -150,10 +150,10 @@ sysInstall() {
 	source _env
 	emerge -1 sys-apps/misybag-baselayout || exit 1
 	if [[ -L "${SYSROOT}" ]]; then
-		echo $(eval_gettext "Toolchain directory is a link. Building environment is not clean.") >&2
+		echo -e $(eval_gettext "Toolchain directory is a link. Building environment is not clean.") >&2
 		exit 1
 	elif [[ ! -d "${SYSROOT}" ]]; then
-		echo $(eval_gettext "Missing toolchain directory \${SYSROOT}") >&2
+		echo -e $(eval_gettext "Missing toolchain directory \${SYSROOT}") >&2
 		exit 1
 	fi
 	rm -rf "${SYSROOT}"/etc/portage
@@ -203,7 +203,7 @@ case ${action} in
 		update "${@}"
 	;;
 	*)
-		echo $(eval_gettext "Unknown action \${action}.") >&2
+		echo -e $(eval_gettext "Unknown action \${action}.") >&2
 		echo
 		help ${0}
 		exit 1
